[workspace]
members = ["comic-text-detector", "koharu", "lama", "manga-ocr"]
resolver = "3"

[workspace.package]
version = "0.2.0-alpha.0"
edition = "2024"
description = "Manga translation tools"
license-file = "LICENSE"
authors = ["Mayo Takanashi <mayo@linux.com>"]
readme = "README.md"
homepage = "https://koharu.rs"
repository = "https://github.com/mayocream/koharu"
keywords = ["manga", "ocr", "translation", "deep_learning", "computer_vision"]

[workspace.dependencies]
candle-transformers = "0.9"
hf-hub = "0.4"
image = "0.25"
ort = { version = "=2.0.0-rc.10", features = ["cuda"] }
anyhow = "1.0"
ndarray = "0.16"
imageproc = "0.25"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.44", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
log = "0.4"
slint = "1.13"
slint-build = "1.13"
