[package]
name = "koharu"
version.workspace = true
edition.workspace = true
description.workspace = true
license-file.workspace = true
authors.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
slint = { workspace = true }
anyhow = { workspace = true }
ort = { workspace = true }
rfd = { workspace = true }
open = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

comic-text-detector = { path = "../comic-text-detector" }
manga-ocr = { path = "../manga-ocr" }
lama = { path = "../lama" }

[build-dependencies]
slint-build = { workspace = true }
