name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        shell: bash
        run: cargo build -p koharu --release --verbose
      - name: Bundle
        shell: bash
        working-directory: target/release
        run: |
          7z a koharu-windows.zip koharu.exe *.dll
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/koharu-windows.zip
